resources/views/partials/header.blade.php, resources/views/shop/contact.blade.php, routes/web.php
=> Feature1#view sign in sign up

resources/views/access/shopdog/accessoriescat.blade.php, resources/views/access/shopdog/accessoriesdog.blade.php, resources/views/pethouse/cat.blade.php, resources/views/pethouse/dog.blade.php, resources/views/petspa/spa.blade.php
=> Bổ sung phần shopp accessories và thêm phần sản phẩm chó mèo

resources/views/partials/footer.blade.php, resources/views/shop/about.blade.php, resources/views/shop/index.blade.php
=> update about index footer

public/css/index.css, resources/views/partials/header.blade.php, resources/views/shop/cart.blade.php, resources/views/shop/index.blade.php
=> modal index, update cart, none hover icon cat +login

public/css/accessories-product.css, public/css/contact.css, public/css/pet-spa.css, public/js/about.js, resources/views/shop/about.blade.php, resources/views/shop/contact.blade.php
=>  thay dổi phông màu

public/css/contact.css, resources/views/pethouse/dog.blade.php, resources/views/shop/contact.blade.php, resources/views/shop/index.blade.php
=> Feature8#fix view product

app/Http/Controllers/HomeController.php, public/css/header.css, public/css/slide_show.css, resources/views/auth/login.blade.php, resources/views/auth/passwords/email.blade.php, resources/views/auth/passwords/reset.blade.php, resources/views/auth/register.blade.php, resources/views/home.blade.php, resources/views/layouts/app.blade.php, resources/views/partials/header.blade.php, resources/views/partials/slideshow.blade.php, resources/views/shop/contact.blade.php, routes/web.php
=> update home slider

database/seeds/ArticleTableSeeder.php
=>  tạo seeder của article

app/Http/Controllers/ArticleController.php, resources/views/dashboard/article/confirm_delete.blade.php, resources/views/dashboard/article/edit.blade.php, resources/views/dashboard/article/form.blade.php, resources/views/dashboard/article/list.blade.php, routes/web.php
=> add them sua xoa article

resources/views/dashboard/product/edit.blade.php, resources/views/dashboard/product/form.blade.php, resources/views/dashboard/product/list.blade.php
=> Feature13.2#add product

app/Http/Controllers/ProductController.php
=> Feature13.2.1#write functions in controller

app/Http/Controllers/ProductController.php, resources/views/dashboard/product/edit.blade.php
Phần sửa sản phẩm .a duyệt giúp e ✌️
=> Feature13.3#edit product

app/Http/Controllers/ProductController.php, resources/views/dashboard/layout/masteradminlayout.blade.php, resources/views/dashboard/product/edit.blade.php, resources/views/dashboard/product/form.blade.php, resources/views/dashboard/product/list.blade.php, routes/web.php
=> Feature13.4#show product

app/Http/Controllers/CategoryController.php, resources/views/dashboard/category/edit.blade.php, resources/views/dashboard/category/form.blade.php, resources/views/dashboard/category/list.blade.php, resources/views/dashboard/layout/masteradminlayout.blade.php
đã ok a ơi. 
thắp hương đc luôn
=> Feature#12.2 category controller

app/Http/Controllers/ProductController.php
a duyệt giúp e ✌️ cố modal nhưng mà chưa đc !
=>  Xoá mềm - dạng update status

resources/views/dashboard/category/form.blade.php
=> validate categoryController

app/Http/Controllers/ProductController.php, resources/views/dashboard/product/form.blade.php, resources/views/dashboard/product/list.blade.php
=> Feature13.6#validate product controller

resources/views/dashboard/article/form.blade.php, resources/views/dashboard/article/list.blade.php
=> Fix lỗi validate và delete sản phẩm phần article controller

resources/views/dashboard/article/edit.blade.php, resources/views/dashboard/article/form.blade.php, resources/views/dashboard/article/list.blade.php, resources/views/dashboard/category/edit.blade.php, resources/views/dashboard/category/form.blade.php, resources/views/dashboard/category/list.blade.php, resources/views/dashboard/index.blade.php, resources/views/dashboard/layout/masteradminlayout.blade.php, resources/views/dashboard/product/edit.blade.php, resources/views/dashboard/product/form.blade.php, resources/views/dashboard/product/list.blade.php
=> Fix5#active category product article

app/Http/Controllers/ProductsallController.php, composer.lock, resources/views/food-for-pet/food.blade.php, resources/views/shop/index.blade.php, routes/web.php
=> E Fix Phần index

resources/views/shop/index.blade.php
=> Fix7.1#view home

app/Http/Controllers/ArticleController.php, database/seeds/ArticleTableSeeder.php, public/css/header.css, resources/views/breedEncyclopedia/article.blade.php, resources/views/partials/header.blade.php, routes/web.php
=> Fix7#view add breed encyclopdia

public/css/login-register.css, public/css/slide_show.css, resources/views/auth/login.blade.php, resources/views/auth/passwords/email.blade.php, resources/views/auth/passwords/reset.blade.php, resources/views/auth/register.blade.php, resources/views/partials/header.blade.php, resources/views/partials/slideshow.blade.php, resources/views/partials/social-sidebar.blade.php
=> chỉnh sửa giao diên đăng kí đăng nhập

resources/views/partials/header.blade.php
=> Fix Header

app/Http/Controllers/UserController.php, resources/views/dashboard/user/edit.blade.php, resources/views/dashboard/user/form.blade.php, resources/views/dashboard/user/list.blade.php, resources/views/detail/detail-product.blade.php
=> Feature19.1#craete user controller

resources/views/dashboard/layout/masteradminlayout.blade.php, resources/views/dashboard/user/list.blade.php, routes/web.php
=> Feature19.3#list user

resources/views/dashboard/user/edit.blade.php
=> Theem Edit cho user

resources/views/dashboard/layout/masteradminlayout.blade.php
em làm active cho phần order rồi đấy
=> active order view

app/Http/Controllers/ProductController.php, resources/views/dashboard/product/edit.blade.php
=> Fix edit product

resources/views/dashboard/layout/masteradminlayout.blade.php
=> fix active chart

resources/views/access/shopaccessories/accessoriesdog.blade.php, resources/views/detail/detail-accessories.blade.php, resources/views/detail/detail-cat.blade.php, resources/views/detail/detail-dog.blade.php, resources/views/detail/detail-food.blade.php, resources/views/food-for-pet/food.blade.php, resources/views/pethouse/cat.blade.php, resources/views/pethouse/dog.blade.php
=> Thêm vào giỏ hàng phần chi tiết sản phẩm

app/Http/Controllers/UserController.php, resources/views/dashboard/user/edit.blade.php
=> Fix lai phan sua user

app/BookSpa.php, app/Contact.php, app/Http/Controllers/ContactController.php, app/Http/Controllers/SpaController.php, database/migrations/2018_08_27_080525_create_contacts_table.php, resources/views/shop/contact.blade.php, routes/web.php
=> Feature18.2#verify contact

resources/views/partials/footer.blade.php, routes/web.php
=> Fix lai footer

app/Http/Controllers/ProductsallController.php, resources/views/partials/header.blade.php, resources/views/partials/search.blade.php, routes/web.php
=> search San pham theo ten or gia

app/Http/Controllers/ContactController.php, app/Http/Controllers/OrderController.php, app/Http/Controllers/ShoppingCartController.php, app/Http/Controllers/SpaController.php, app/Http/Controllers/VerifyContactController.php, resources/views/mail/confirmed.blade.php, resources/views/mail/verifyContact.blade.php, resources/views/mail/verifyRequest.blade.php, resources/views/partials/header.blade.php, resources/views/shop/history-order.blade.php, routes/web.php
=> Feature24#view order

resources/views/partials/header.blade.php
=> chỉnh lại url từ lịch sử giao dịch chuyển về page spa

resources/views/home.blade.php, resources/views/shop/history-order.blade.php
=> thêm linh về mua sp khi k có lịch sử

app/Http/Controllers/OrderController.php, resources/views/dashboard/charts/chart.blade.php
=> Fix21#search chart

app/Http/Controllers/CategoryController.php, app/Http/Controllers/ProductController.php, resources/views/dashboard/product/list.blade.php, routes/web.php
=> checkbox all product and delete

app/Http/Controllers/ArticleController.php, resources/views/dashboard/article/list.blade.php, routes/web.php
=> checkbox all article and delete

resources/views/dashboard/order/list.blade.php
=> Feature26.4#checkout order

app/Http/Controllers/ProductsallController.php, app/Http/Controllers/ShoppingCartController.php, resources/views/access/shopaccessories/accessoriesdog.blade.php, resources/views/dashboard/article/list.blade.php, resources/views/dashboard/category/list.blade.php, resources/views/dashboard/product/list.blade.php, resources/views/dashboard/user/list.blade.php, resources/views/food-for-pet/food.blade.php, resources/views/partials/search.blade.php, resources/views/pethouse/cat.blade.php, resources/views/pethouse/dog.blade.php
=> Fix22#search price product

resources/views/shop/history-order.blade.php
=> chỉnh sửa lại list của lịch sử mua hàng của web

app/Http/Controllers/SpaController.php, app/Http/Controllers/VerifyContactController.php, app/Http/Controllers/VerifyController.php, resources/views/mail/verifyBookSpa.php, routes/web.php
=> Fix Send Email and remove some not use

app/BookSpa.php, app/Http/Controllers/SpaDashboardController.php, resources/views/error/400.blade.php, routes/web.php
=> Add Spa Dashboard
